using  System;
using  System.Collections.Generic;
using  System.Linq.Expressions;
using  System.Web;
using  Umbraco.Core.Models;
using  Umbraco.Core.Models.PublishedContent;
using  Umbraco.Web;
using  Umbraco.ModelsBuilder;
using  Umbraco.ModelsBuilder.Umbraco;
[assembly: PureLiveAssembly]
[assembly:ModelsBuilderAssembly(PureLive = true, SourceHash = "e135453de33fe88")]
[assembly:System.Reflection.AssemblyVersion("0.0.0.2")]


// FILE: models.generated.cs

//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------















namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>BaseType</summary>
	[PublishedContentModel("baseType")]
	public partial class BaseType : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "baseType";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BaseType(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BaseType, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Audio File
		///</summary>
		[ImplementPropertyType("global_Audio")]
		public IPublishedContent Global_Audio
		{
			get { return this.GetPropertyValue<IPublishedContent>("global_Audio"); }
		}

		///<summary>
		/// Header Image
		///</summary>
		[ImplementPropertyType("global_HeaderImage")]
		public IPublishedContent Global_HeaderImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("global_HeaderImage"); }
		}

		///<summary>
		/// Offer
		///</summary>
		[ImplementPropertyType("global_Offer")]
		public IEnumerable<IPublishedContent> Global_Offer
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("global_Offer"); }
		}

		///<summary>
		/// Slogan
		///</summary>
		[ImplementPropertyType("global_Slogan")]
		public string Global_Slogan
		{
			get { return this.GetPropertyValue<string>("global_Slogan"); }
		}

		///<summary>
		/// meta_author
		///</summary>
		[ImplementPropertyType("meta_author")]
		public string Meta_author
		{
			get { return this.GetPropertyValue<string>("meta_author"); }
		}

		///<summary>
		/// meta_description
		///</summary>
		[ImplementPropertyType("meta_Description")]
		public string Meta_Description
		{
			get { return this.GetPropertyValue<string>("meta_Description"); }
		}

		///<summary>
		/// meta_googlebot
		///</summary>
		[ImplementPropertyType("meta_googlebot")]
		public string Meta_googlebot
		{
			get { return this.GetPropertyValue<string>("meta_googlebot"); }
		}

		///<summary>
		/// meta_keywords
		///</summary>
		[ImplementPropertyType("meta_keywords")]
		public string Meta_keywords
		{
			get { return this.GetPropertyValue<string>("meta_keywords"); }
		}

		///<summary>
		/// meta_ogDescription
		///</summary>
		[ImplementPropertyType("meta_ogDescription")]
		public string Meta_ogDescription
		{
			get { return this.GetPropertyValue<string>("meta_ogDescription"); }
		}

		///<summary>
		/// meta_ogImage
		///</summary>
		[ImplementPropertyType("meta_ogImage")]
		public IPublishedContent Meta_ogImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("meta_ogImage"); }
		}

		///<summary>
		/// meta_ogTitle
		///</summary>
		[ImplementPropertyType("meta_ogTitle")]
		public string Meta_ogTitle
		{
			get { return this.GetPropertyValue<string>("meta_ogTitle"); }
		}

		///<summary>
		/// meta_ogType
		///</summary>
		[ImplementPropertyType("meta_ogType")]
		public string Meta_ogType
		{
			get { return this.GetPropertyValue<string>("meta_ogType"); }
		}

		///<summary>
		/// meta_ogUrl
		///</summary>
		[ImplementPropertyType("meta_ogUrl")]
		public string Meta_ogUrl
		{
			get { return this.GetPropertyValue<string>("meta_ogUrl"); }
		}

		///<summary>
		/// Hide Children in Menu
		///</summary>
		[ImplementPropertyType("navihidechildren")]
		public bool Navihidechildren
		{
			get { return this.GetPropertyValue<bool>("navihidechildren"); }
		}

		///<summary>
		/// Page Name (Alias)
		///</summary>
		[ImplementPropertyType("page_Alias")]
		public string Page_Alias
		{
			get { return this.GetPropertyValue<string>("page_Alias"); }
		}

		///<summary>
		/// Dashboard
		///</summary>
		[ImplementPropertyType("rankone_checker")]
		public object Rankone_checker
		{
			get { return this.GetPropertyValue("rankone_checker"); }
		}

		///<summary>
		/// Preview
		///</summary>
		[ImplementPropertyType("rankone_preview")]
		public object Rankone_preview
		{
			get { return this.GetPropertyValue("rankone_preview"); }
		}

		///<summary>
		/// Hide From Navigation
		///</summary>
		[ImplementPropertyType("umbraconavihide")]
		public bool Umbraconavihide
		{
			get { return this.GetPropertyValue<bool>("umbraconavihide"); }
		}
	}

	/// <summary>PartialType</summary>
	[PublishedContentModel("partialType")]
	public partial class PartialType : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "partialType";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public PartialType(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PartialType, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>HomeSliderItem</summary>
	[PublishedContentModel("homeSliderItem")]
	public partial class HomeSliderItem : PartialType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "homeSliderItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HomeSliderItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HomeSliderItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Delay (in milliseconds): 3000 ms = 3 sec
		///</summary>
		[ImplementPropertyType("sliderItem_delay")]
		public int SliderItem_delay
		{
			get { return this.GetPropertyValue<int>("sliderItem_delay"); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("slideritem_Description")]
		public IHtmlString Slideritem_Description
		{
			get { return this.GetPropertyValue<IHtmlString>("slideritem_Description"); }
		}

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("slideritem_Image")]
		public IPublishedContent Slideritem_Image
		{
			get { return this.GetPropertyValue<IPublishedContent>("slideritem_Image"); }
		}

		///<summary>
		/// Link
		///</summary>
		[ImplementPropertyType("slideritem_Link")]
		public string Slideritem_Link
		{
			get { return this.GetPropertyValue<string>("slideritem_Link"); }
		}

		///<summary>
		/// Show Request Button
		///</summary>
		[ImplementPropertyType("slideritem_RequestButton")]
		public bool Slideritem_RequestButton
		{
			get { return this.GetPropertyValue<bool>("slideritem_RequestButton"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("slideritem_Title")]
		public string Slideritem_Title
		{
			get { return this.GetPropertyValue<string>("slideritem_Title"); }
		}

		///<summary>
		/// Youtube Video ID
		///</summary>
		[ImplementPropertyType("sliderItem_youtubeID")]
		public string SliderItem_youtubeID
		{
			get { return this.GetPropertyValue<string>("sliderItem_youtubeID"); }
		}
	}

	/// <summary>Home</summary>
	[PublishedContentModel("home")]
	public partial class Home : BaseType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "home";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Home(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// About Next Home
		///</summary>
		[ImplementPropertyType("home_AboutNextHome")]
		public IHtmlString Home_AboutNextHome
		{
			get { return this.GetPropertyValue<IHtmlString>("home_AboutNextHome"); }
		}

		///<summary>
		/// Hotline Image: 2514 x 670
		///</summary>
		[ImplementPropertyType("home_HotlineImage")]
		public IPublishedContent Home_HotlineImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("home_HotlineImage"); }
		}

		///<summary>
		/// home_IconBox
		///</summary>
		[ImplementPropertyType("home_IconBox")]
		public IEnumerable<IPublishedContent> Home_IconBox
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("home_IconBox"); }
		}

		///<summary>
		/// Loading GIF
		///</summary>
		[ImplementPropertyType("home_LoadingGIF")]
		public IPublishedContent Home_LoadingGif
		{
			get { return this.GetPropertyValue<IPublishedContent>("home_LoadingGIF"); }
		}

		///<summary>
		/// Logo: 612 x 114
		///</summary>
		[ImplementPropertyType("home_Logo")]
		public IPublishedContent Home_Logo
		{
			get { return this.GetPropertyValue<IPublishedContent>("home_Logo"); }
		}

		///<summary>
		/// Projects
		///</summary>
		[ImplementPropertyType("home_Projects")]
		public Newtonsoft.Json.Linq.JToken Home_Projects
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("home_Projects"); }
		}

		///<summary>
		/// Site Name
		///</summary>
		[ImplementPropertyType("home_SiteName")]
		public string Home_SiteName
		{
			get { return this.GetPropertyValue<string>("home_SiteName"); }
		}

		///<summary>
		/// Slider
		///</summary>
		[ImplementPropertyType("home_Slider")]
		public IEnumerable<IPublishedContent> Home_Slider
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("home_Slider"); }
		}

		///<summary>
		/// Slider Delay (milliseconds): 3000 ms = 3 sec
		///</summary>
		[ImplementPropertyType("home_SliderDelay")]
		public int Home_SliderDelay
		{
			get { return this.GetPropertyValue<int>("home_SliderDelay"); }
		}
	}

	/// <summary>Project</summary>
	[PublishedContentModel("project")]
	public partial class Project : BaseType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "project";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Project(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Project, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Area From
		///</summary>
		[ImplementPropertyType("project_AreaFrom")]
		public decimal Project_AreaFrom
		{
			get { return this.GetPropertyValue<decimal>("project_AreaFrom"); }
		}

		///<summary>
		/// Area To
		///</summary>
		[ImplementPropertyType("project_AreaTo")]
		public decimal Project_AreaTo
		{
			get { return this.GetPropertyValue<decimal>("project_AreaTo"); }
		}

		///<summary>
		/// Brochure
		///</summary>
		[ImplementPropertyType("project_Brochure")]
		public IPublishedContent Project_Brochure
		{
			get { return this.GetPropertyValue<IPublishedContent>("project_Brochure"); }
		}

		///<summary>
		/// City
		///</summary>
		[ImplementPropertyType("project_City")]
		public object Project_City
		{
			get { return this.GetPropertyValue("project_City"); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("project_Description")]
		public IHtmlString Project_Description
		{
			get { return this.GetPropertyValue<IHtmlString>("project_Description"); }
		}

		///<summary>
		/// District
		///</summary>
		[ImplementPropertyType("project_District")]
		public object Project_District
		{
			get { return this.GetPropertyValue("project_District"); }
		}

		///<summary>
		/// Facilities
		///</summary>
		[ImplementPropertyType("project_Facilities")]
		public nuPickers.Picker Project_Facilities
		{
			get { return this.GetPropertyValue<nuPickers.Picker>("project_Facilities"); }
		}

		///<summary>
		/// Full Address
		///</summary>
		[ImplementPropertyType("project_FullAddress")]
		public string Project_FullAddress
		{
			get { return this.GetPropertyValue<string>("project_FullAddress"); }
		}

		///<summary>
		/// Images: 767 x 442
		///</summary>
		[ImplementPropertyType("project_Images")]
		public IEnumerable<IPublishedContent> Project_Images
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("project_Images"); }
		}

		///<summary>
		/// Latitude
		///</summary>
		[ImplementPropertyType("project_Latitude")]
		public decimal Project_Latitude
		{
			get { return this.GetPropertyValue<decimal>("project_Latitude"); }
		}

		///<summary>
		/// Logo
		///</summary>
		[ImplementPropertyType("project_Logo")]
		public IPublishedContent Project_Logo
		{
			get { return this.GetPropertyValue<IPublishedContent>("project_Logo"); }
		}

		///<summary>
		/// Longitude
		///</summary>
		[ImplementPropertyType("project_Longitude")]
		public decimal Project_Longitude
		{
			get { return this.GetPropertyValue<decimal>("project_Longitude"); }
		}

		///<summary>
		/// Main Image: 767 x 442
		///</summary>
		[ImplementPropertyType("project_MainImage")]
		public IPublishedContent Project_MainImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("project_MainImage"); }
		}

		///<summary>
		/// Map Icon
		///</summary>
		[ImplementPropertyType("project_MapMarker")]
		public IPublishedContent Project_MapMarker
		{
			get { return this.GetPropertyValue<IPublishedContent>("project_MapMarker"); }
		}

		///<summary>
		/// Price From
		///</summary>
		[ImplementPropertyType("project_PriceFrom")]
		public decimal Project_PriceFrom
		{
			get { return this.GetPropertyValue<decimal>("project_PriceFrom"); }
		}

		///<summary>
		/// Price To
		///</summary>
		[ImplementPropertyType("project_PriceTo")]
		public decimal Project_PriceTo
		{
			get { return this.GetPropertyValue<decimal>("project_PriceTo"); }
		}

		///<summary>
		/// Project Type
		///</summary>
		[ImplementPropertyType("project_Type")]
		public nuPickers.Picker Project_Type
		{
			get { return this.GetPropertyValue<nuPickers.Picker>("project_Type"); }
		}

		///<summary>
		/// Videos
		///</summary>
		[ImplementPropertyType("project_Videos")]
		public Newtonsoft.Json.Linq.JToken Project_Videos
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("project_Videos"); }
		}
	}

	// Mixin content Type 1094 with alias "dummy"
	/// <summary>NonPage</summary>
	public partial interface IDummy : IPublishedContent
	{
		/// <summary>Hidden</summary>
		bool Umbraconavihide { get; }
	}

	/// <summary>NonPage</summary>
	[PublishedContentModel("dummy")]
	public partial class Dummy : PublishedContentModel, IDummy
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "dummy";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Dummy(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Dummy, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Hidden
		///</summary>
		[ImplementPropertyType("umbraconavihide")]
		public bool Umbraconavihide
		{
			get { return GetUmbraconavihide(this); }
		}

		/// <summary>Static getter for Hidden</summary>
		public static bool GetUmbraconavihide(IDummy that) { return that.GetPropertyValue<bool>("umbraconavihide"); }
	}

	/// <summary>ProjectsList</summary>
	[PublishedContentModel("projectsList")]
	public partial class ProjectsList : Dummy
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "projectsList";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ProjectsList(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ProjectsList, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Calssify By Type
		///</summary>
		[ImplementPropertyType("projectslist_CalssifyByType")]
		public bool Projectslist_CalssifyByType
		{
			get { return this.GetPropertyValue<bool>("projectslist_CalssifyByType"); }
		}

		///<summary>
		/// Hide Top Menu
		///</summary>
		[ImplementPropertyType("projectslist_HideTopMenu")]
		public bool Projectslist_HideTopMenu
		{
			get { return this.GetPropertyValue<bool>("projectslist_HideTopMenu"); }
		}
	}

	/// <summary>Video</summary>
	[PublishedContentModel("video")]
	public partial class Video : Dummy
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "video";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Video(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Video, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// video_Url
		///</summary>
		[ImplementPropertyType("video_Url")]
		public Videolizer.VideolizerVideo Video_Url
		{
			get { return this.GetPropertyValue<Videolizer.VideolizerVideo>("video_Url"); }
		}
	}

	/// <summary>Unit</summary>
	[PublishedContentModel("unit")]
	public partial class Unit : BaseType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "unit";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Unit(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Unit, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Area
		///</summary>
		[ImplementPropertyType("unit_Area")]
		public decimal Unit_Area
		{
			get { return this.GetPropertyValue<decimal>("unit_Area"); }
		}

		///<summary>
		/// No. Bath Rooms
		///</summary>
		[ImplementPropertyType("unit_BathRooms")]
		public int Unit_BathRooms
		{
			get { return this.GetPropertyValue<int>("unit_BathRooms"); }
		}

		///<summary>
		/// No. Bed Rooms
		///</summary>
		[ImplementPropertyType("unit_BedRooms")]
		public decimal Unit_BedRooms
		{
			get { return this.GetPropertyValue<decimal>("unit_BedRooms"); }
		}

		///<summary>
		/// Category
		///</summary>
		[ImplementPropertyType("unit_Category")]
		public nuPickers.Picker Unit_Category
		{
			get { return this.GetPropertyValue<nuPickers.Picker>("unit_Category"); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("unit_Description")]
		public IHtmlString Unit_Description
		{
			get { return this.GetPropertyValue<IHtmlString>("unit_Description"); }
		}

		///<summary>
		/// Floor
		///</summary>
		[ImplementPropertyType("unit_Floor")]
		public object Unit_Floor
		{
			get { return this.GetPropertyValue("unit_Floor"); }
		}

		///<summary>
		/// Flooring
		///</summary>
		[ImplementPropertyType("unit_Flooring")]
		public object Unit_Flooring
		{
			get { return this.GetPropertyValue("unit_Flooring"); }
		}

		///<summary>
		/// Images
		///</summary>
		[ImplementPropertyType("unit_Images")]
		public IEnumerable<IPublishedContent> Unit_Images
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("unit_Images"); }
		}

		///<summary>
		/// Featured
		///</summary>
		[ImplementPropertyType("unit_IsFeatured")]
		public bool Unit_IsFeatured
		{
			get { return this.GetPropertyValue<bool>("unit_IsFeatured"); }
		}

		///<summary>
		/// Sold Out
		///</summary>
		[ImplementPropertyType("unit_IsSoldOut")]
		public bool Unit_IsSoldOut
		{
			get { return this.GetPropertyValue<bool>("unit_IsSoldOut"); }
		}

		///<summary>
		/// Main Image
		///</summary>
		[ImplementPropertyType("unit_MainImage")]
		public IPublishedContent Unit_MainImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("unit_MainImage"); }
		}

		///<summary>
		/// Price (in meter)
		///</summary>
		[ImplementPropertyType("unit_Price")]
		public decimal Unit_Price
		{
			get { return this.GetPropertyValue<decimal>("unit_Price"); }
		}

		///<summary>
		/// Total Price
		///</summary>
		[ImplementPropertyType("unit_TotalPrice")]
		public object Unit_TotalPrice
		{
			get { return this.GetPropertyValue("unit_TotalPrice"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("unit_Type")]
		public object Unit_Type
		{
			get { return this.GetPropertyValue("unit_Type"); }
		}
	}

	/// <summary>AboutUs</summary>
	[PublishedContentModel("aboutUs")]
	public partial class AboutUs : BaseType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "aboutUs";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public AboutUs(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AboutUs, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// About Us
		///</summary>
		[ImplementPropertyType("aboutus_AboutUs")]
		public IHtmlString Aboutus_AboutUs
		{
			get { return this.GetPropertyValue<IHtmlString>("aboutus_AboutUs"); }
		}

		///<summary>
		/// Images: 570 x 349
		///</summary>
		[ImplementPropertyType("aboutus_Images")]
		public IEnumerable<IPublishedContent> Aboutus_Images
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("aboutus_Images"); }
		}

		///<summary>
		/// Our Mission
		///</summary>
		[ImplementPropertyType("aboutus_OurMission")]
		public IHtmlString Aboutus_OurMission
		{
			get { return this.GetPropertyValue<IHtmlString>("aboutus_OurMission"); }
		}

		///<summary>
		/// Our Values
		///</summary>
		[ImplementPropertyType("aboutus_OurValues")]
		public IHtmlString Aboutus_OurValues
		{
			get { return this.GetPropertyValue<IHtmlString>("aboutus_OurValues"); }
		}

		///<summary>
		/// Our Vision
		///</summary>
		[ImplementPropertyType("aboutus_OurVision")]
		public IHtmlString Aboutus_OurVision
		{
			get { return this.GetPropertyValue<IHtmlString>("aboutus_OurVision"); }
		}

		///<summary>
		/// Video
		///</summary>
		[ImplementPropertyType("aboutus_Video")]
		public Videolizer.VideolizerVideo Aboutus_Video
		{
			get { return this.GetPropertyValue<Videolizer.VideolizerVideo>("aboutus_Video"); }
		}

		///<summary>
		/// Who We Are
		///</summary>
		[ImplementPropertyType("aboutus_WhoWeAre")]
		public IHtmlString Aboutus_WhoWeAre
		{
			get { return this.GetPropertyValue<IHtmlString>("aboutus_WhoWeAre"); }
		}
	}

	/// <summary>PresidentWord</summary>
	[PublishedContentModel("presidentWord")]
	public partial class PresidentWord : BaseType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "presidentWord";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public PresidentWord(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PresidentWord, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Image: 570 x 400
		///</summary>
		[ImplementPropertyType("president_Image")]
		public IPublishedContent President_Image
		{
			get { return this.GetPropertyValue<IPublishedContent>("president_Image"); }
		}

		///<summary>
		/// Name
		///</summary>
		[ImplementPropertyType("president_Name")]
		public string President_Name
		{
			get { return this.GetPropertyValue<string>("president_Name"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("president_Title")]
		public string President_Title
		{
			get { return this.GetPropertyValue<string>("president_Title"); }
		}

		///<summary>
		/// Word
		///</summary>
		[ImplementPropertyType("president_Word")]
		public IHtmlString President_Word
		{
			get { return this.GetPropertyValue<IHtmlString>("president_Word"); }
		}
	}

	/// <summary>OurTeam</summary>
	[PublishedContentModel("ourTeam")]
	public partial class OurTeam : BaseType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "ourTeam";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public OurTeam(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<OurTeam, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>TeamMember</summary>
	[PublishedContentModel("teamMember")]
	public partial class TeamMember : Dummy
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "teamMember";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public TeamMember(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TeamMember, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// About
		///</summary>
		[ImplementPropertyType("member_About")]
		public IHtmlString Member_About
		{
			get { return this.GetPropertyValue<IHtmlString>("member_About"); }
		}

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("member_Email")]
		public string Member_Email
		{
			get { return this.GetPropertyValue<string>("member_Email"); }
		}

		///<summary>
		/// Image: 364 x 388
		///</summary>
		[ImplementPropertyType("member_Image")]
		public IPublishedContent Member_Image
		{
			get { return this.GetPropertyValue<IPublishedContent>("member_Image"); }
		}

		///<summary>
		/// Phone No.
		///</summary>
		[ImplementPropertyType("member_PhoneNo")]
		public string Member_PhoneNo
		{
			get { return this.GetPropertyValue<string>("member_PhoneNo"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("member_Title")]
		public object Member_Title
		{
			get { return this.GetPropertyValue("member_Title"); }
		}
	}

	/// <summary>News</summary>
	[PublishedContentModel("news")]
	public partial class News : BaseType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "news";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public News(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<News, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>NewsItem</summary>
	[PublishedContentModel("newsItem")]
	public partial class NewsItem : BaseType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "newsItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public NewsItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NewsItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("newsitem_Description")]
		public IHtmlString Newsitem_Description
		{
			get { return this.GetPropertyValue<IHtmlString>("newsitem_Description"); }
		}

		///<summary>
		/// Gallery: 767 x 442
		///</summary>
		[ImplementPropertyType("newsitem_Gallery")]
		public IEnumerable<IPublishedContent> Newsitem_Gallery
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("newsitem_Gallery"); }
		}

		///<summary>
		/// Main Image: 767 x 442
		///</summary>
		[ImplementPropertyType("newsitem_MainImage")]
		public IPublishedContent Newsitem_MainImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("newsitem_MainImage"); }
		}

		///<summary>
		/// Videos
		///</summary>
		[ImplementPropertyType("newsitem_Videos")]
		public Newtonsoft.Json.Linq.JToken Newsitem_Videos
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("newsitem_Videos"); }
		}
	}

	/// <summary>ProjectTimeline</summary>
	[PublishedContentModel("projectTimeline")]
	public partial class ProjectTimeline : PartialType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "projectTimeline";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ProjectTimeline(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ProjectTimeline, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Date
		///</summary>
		[ImplementPropertyType("timeline_Date")]
		public DateTime Timeline_Date
		{
			get { return this.GetPropertyValue<DateTime>("timeline_Date"); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("timeline_Description")]
		public IHtmlString Timeline_Description
		{
			get { return this.GetPropertyValue<IHtmlString>("timeline_Description"); }
		}

		///<summary>
		/// Images: 530 x 200
		///</summary>
		[ImplementPropertyType("timeline_Images")]
		public IEnumerable<IPublishedContent> Timeline_Images
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("timeline_Images"); }
		}
	}

	/// <summary>RankOne - Seo Composition</summary>
	[PublishedContentModel("rankOneSeoComposition")]
	public partial class RankOneSeoComposition : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "rankOneSeoComposition";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public RankOneSeoComposition(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<RankOneSeoComposition, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Meta description: A brief description of the content on your page. This text is shown below the title in a google search result. The ideal length is between 50 and 150 characters
		///</summary>
		[ImplementPropertyType("seoMetaDescription")]
		public string SeoMetaDescription
		{
			get { return this.GetPropertyValue<string>("seoMetaDescription"); }
		}

		///<summary>
		/// Meta keywords: Keywords that describe the content of the page. This is considered optional since most modern search engines don't use this anymore
		///</summary>
		[ImplementPropertyType("seoMetaKeywords")]
		public IEnumerable<string> SeoMetaKeywords
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("seoMetaKeywords"); }
		}

		///<summary>
		/// Title: The title of the page, this is also the first text in a google search result. The ideal length is shorter than 60 characters
		///</summary>
		[ImplementPropertyType("seoTitle")]
		public string SeoTitle
		{
			get { return this.GetPropertyValue<string>("seoTitle"); }
		}
	}

	/// <summary>ContactUs</summary>
	[PublishedContentModel("contactUs")]
	public partial class ContactUs : BaseType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contactUs";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContactUs(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContactUs, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Company Address
		///</summary>
		[ImplementPropertyType("contactus_Address")]
		public string Contactus_Address
		{
			get { return this.GetPropertyValue<string>("contactus_Address"); }
		}

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("contactus_Email")]
		public string Contactus_Email
		{
			get { return this.GetPropertyValue<string>("contactus_Email"); }
		}

		///<summary>
		/// Facebook
		///</summary>
		[ImplementPropertyType("contactus_Facebook")]
		public string Contactus_Facebook
		{
			get { return this.GetPropertyValue<string>("contactus_Facebook"); }
		}

		///<summary>
		/// Hotline
		///</summary>
		[ImplementPropertyType("contactus_Hotline")]
		public string Contactus_Hotline
		{
			get { return this.GetPropertyValue<string>("contactus_Hotline"); }
		}

		///<summary>
		/// Instagram
		///</summary>
		[ImplementPropertyType("contactus_Instagram")]
		public string Contactus_Instagram
		{
			get { return this.GetPropertyValue<string>("contactus_Instagram"); }
		}

		///<summary>
		/// Latitude
		///</summary>
		[ImplementPropertyType("contactus_Latitude")]
		public decimal Contactus_Latitude
		{
			get { return this.GetPropertyValue<decimal>("contactus_Latitude"); }
		}

		///<summary>
		/// LinkedIn
		///</summary>
		[ImplementPropertyType("contactus_LinkedIn")]
		public string Contactus_LinkedIn
		{
			get { return this.GetPropertyValue<string>("contactus_LinkedIn"); }
		}

		///<summary>
		/// Longitude
		///</summary>
		[ImplementPropertyType("contactus_Longitude")]
		public decimal Contactus_Longitude
		{
			get { return this.GetPropertyValue<decimal>("contactus_Longitude"); }
		}

		///<summary>
		/// Map Icon
		///</summary>
		[ImplementPropertyType("contactus_MapMarker")]
		public IPublishedContent Contactus_MapMarker
		{
			get { return this.GetPropertyValue<IPublishedContent>("contactus_MapMarker"); }
		}

		///<summary>
		/// Land line
		///</summary>
		[ImplementPropertyType("contactus_Phone")]
		public string Contactus_Phone
		{
			get { return this.GetPropertyValue<string>("contactus_Phone"); }
		}

		///<summary>
		/// Twitter
		///</summary>
		[ImplementPropertyType("contactus_Twitter")]
		public string Contactus_Twitter
		{
			get { return this.GetPropertyValue<string>("contactus_Twitter"); }
		}

		///<summary>
		/// Whats App
		///</summary>
		[ImplementPropertyType("contactus_WhatsApp")]
		public string Contactus_WhatsApp
		{
			get { return this.GetPropertyValue<string>("contactus_WhatsApp"); }
		}

		///<summary>
		/// WhatsApp Message
		///</summary>
		[ImplementPropertyType("contactus_whatsapptext")]
		public string Contactus_whatsapptext
		{
			get { return this.GetPropertyValue<string>("contactus_whatsapptext"); }
		}

		///<summary>
		/// Youtube
		///</summary>
		[ImplementPropertyType("contactus_Youtube")]
		public string Contactus_Youtube
		{
			get { return this.GetPropertyValue<string>("contactus_Youtube"); }
		}
	}

	/// <summary>IconBox</summary>
	[PublishedContentModel("iconBox")]
	public partial class IconBox : Dummy
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "iconBox";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public IconBox(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<IconBox, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Icon
		///</summary>
		[ImplementPropertyType("iconbox_icon")]
		public string Iconbox_icon
		{
			get { return this.GetPropertyValue<string>("iconbox_icon"); }
		}

		///<summary>
		/// Text
		///</summary>
		[ImplementPropertyType("iconbox_text")]
		public string Iconbox_text
		{
			get { return this.GetPropertyValue<string>("iconbox_text"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("iconbox_title")]
		public string Iconbox_title
		{
			get { return this.GetPropertyValue<string>("iconbox_title"); }
		}

		///<summary>
		/// Value
		///</summary>
		[ImplementPropertyType("iconbox_value")]
		public string Iconbox_value
		{
			get { return this.GetPropertyValue<string>("iconbox_value"); }
		}
	}

	/// <summary>ImageGallery</summary>
	[PublishedContentModel("imageGallery")]
	public partial class ImageGallery : BaseType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "imageGallery";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ImageGallery(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ImageGallery, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>VideoGallery</summary>
	[PublishedContentModel("videoGallery")]
	public partial class VideoGallery : BaseType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "videoGallery";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public VideoGallery(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<VideoGallery, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>ProjectUpdates</summary>
	[PublishedContentModel("projectUpdates")]
	public partial class ProjectUpdates : BaseType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "projectUpdates";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ProjectUpdates(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ProjectUpdates, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Building</summary>
	[PublishedContentModel("building")]
	public partial class Building : BaseType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "building";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Building(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Building, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("building_Image")]
		public IPublishedContent Building_Image
		{
			get { return this.GetPropertyValue<IPublishedContent>("building_Image"); }
		}
	}

	/// <summary>SearchUnits</summary>
	[PublishedContentModel("searchUnits")]
	public partial class SearchUnits : Dummy
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "searchUnits";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SearchUnits(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SearchUnits, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>JobVacancy</summary>
	[PublishedContentModel("jobVacancy")]
	public partial class JobVacancy : PartialType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "jobVacancy";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public JobVacancy(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<JobVacancy, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("job_Description")]
		public IHtmlString Job_Description
		{
			get { return this.GetPropertyValue<IHtmlString>("job_Description"); }
		}

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("job_Email")]
		public string Job_Email
		{
			get { return this.GetPropertyValue<string>("job_Email"); }
		}
	}

	/// <summary>Jobs</summary>
	[PublishedContentModel("jobs")]
	public partial class Jobs : BaseType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "jobs";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Jobs(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Jobs, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Brief
		///</summary>
		[ImplementPropertyType("jobs_Brief")]
		public IHtmlString Jobs_Brief
		{
			get { return this.GetPropertyValue<IHtmlString>("jobs_Brief"); }
		}
	}

	/// <summary>Offer</summary>
	[PublishedContentModel("offer")]
	public partial class Offer : Dummy
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "offer";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Offer(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Offer, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Hide After: Default: never hide
		///</summary>
		[ImplementPropertyType("offer_hideAfter")]
		public int Offer_hideAfter
		{
			get { return this.GetPropertyValue<int>("offer_hideAfter"); }
		}

		///<summary>
		/// offer_Image
		///</summary>
		[ImplementPropertyType("offer_Image")]
		public IPublishedContent Offer_Image
		{
			get { return this.GetPropertyValue<IPublishedContent>("offer_Image"); }
		}

		///<summary>
		/// Link Url
		///</summary>
		[ImplementPropertyType("offer_LinkUrl")]
		public string Offer_LinkUrl
		{
			get { return this.GetPropertyValue<string>("offer_LinkUrl"); }
		}

		///<summary>
		/// Mobile Image
		///</summary>
		[ImplementPropertyType("offer_MobileImage")]
		public IPublishedContent Offer_MobileImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("offer_MobileImage"); }
		}

		///<summary>
		/// Name
		///</summary>
		[ImplementPropertyType("offer_Name")]
		public string Offer_Name
		{
			get { return this.GetPropertyValue<string>("offer_Name"); }
		}

		///<summary>
		/// Show After (milliseconds): Default: 3000 ms
		///</summary>
		[ImplementPropertyType("offer_showAfter")]
		public int Offer_showAfter
		{
			get { return this.GetPropertyValue<int>("offer_showAfter"); }
		}
	}

	/// <summary>OffersList</summary>
	[PublishedContentModel("offersList")]
	public partial class OffersList : BaseType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "offersList";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public OffersList(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<OffersList, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>ErrorPage</summary>
	[PublishedContentModel("errorPage")]
	public partial class ErrorPage : BaseType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "errorPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ErrorPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ErrorPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Test</summary>
	[PublishedContentModel("test")]
	public partial class Test : PublishedContentModel, IDummy
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "test";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Test(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Test, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Hidden
		///</summary>
		[ImplementPropertyType("umbraconavihide")]
		public bool Umbraconavihide
		{
			get { return Umbraco.Web.PublishedContentModels.Dummy.GetUmbraconavihide(this); }
		}
	}

	/// <summary>Folder</summary>
	[PublishedContentModel("Folder")]
	public partial class Folder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Folder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Folder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Folder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contents:
		///</summary>
		[ImplementPropertyType("contents")]
		public object Contents
		{
			get { return this.GetPropertyValue("contents"); }
		}
	}

	/// <summary>Image</summary>
	[PublishedContentModel("Image")]
	public partial class Image : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Image";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Image(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Image, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload image
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("umbracoHeight")]
		public string UmbracoHeight
		{
			get { return this.GetPropertyValue<string>("umbracoHeight"); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public string UmbracoWidth
		{
			get { return this.GetPropertyValue<string>("umbracoWidth"); }
		}
	}

	/// <summary>File</summary>
	[PublishedContentModel("File")]
	public partial class File : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "File";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public File(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<File, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload file
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public string UmbracoFile
		{
			get { return this.GetPropertyValue<string>("umbracoFile"); }
		}
	}

	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Address
		///</summary>
		[ImplementPropertyType("member_Address")]
		public string Member_Address
		{
			get { return this.GetPropertyValue<string>("member_Address"); }
		}

		///<summary>
		/// Nationality
		///</summary>
		[ImplementPropertyType("member_Nationality")]
		public string Member_Nationality
		{
			get { return this.GetPropertyValue<string>("member_Nationality"); }
		}

		///<summary>
		/// Phone
		///</summary>
		[ImplementPropertyType("member_Phone")]
		public string Member_Phone
		{
			get { return this.GetPropertyValue<string>("member_Phone"); }
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}

}



// EOF
